version: '3'

services:
  django_api:
    volumes:
      - static:/static
    env_file:
        - .env
    environment:
      - HOST=0.0.0.0
      - DEBUG=False
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_HOST=db
#      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    depends_on:
      - db
    build:
      context: .
    ports:
      - "8000:8000"
    command:
      - /bin/bash      # add this line to specify the shell to use
      - -c            # add this line to specify the command to run
      - |
        chmod +x /create_superuser.sh && \
        /create_superuser.sh &&
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_api


volumes :
  static: